apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xz18u2gv6-java-quarkus
  janus-idp.io/tekton: xz18u2gv6-java-quarkus
  backstage.io/kubernetes-id: xz18u2gv6-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xz18u2gv6-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
